[project]
name = "scp-video"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Martin Vasquez", email = "159503418+martinvasquez1@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
    "manim>=0.21.0",
]

[project.scripts]
scp-video = "scp_video:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
